### PR TITLE
Fix EZP-26113: session id is regenerated when publishing content

### PR DESCRIPTION
**Pull request by joaoinacio**
JIRA: https://jira.ez.no/browse/EZP-26113

### CODE REVIEW

**Comment by glye** [comment]
Nice! Tentative +1 - it looks too easy :) Am curious why this is not reported until now - doesn't it happen in pure legacy setups?

**Comment by joaoinacio** [comment]
It does happen in pure legacy (tested in 5.4.7)

**Comment by yannickroger** [comment]
+1 if the behavior doesn't happen on legacy without ezflow activated

**Comment by andrerom** [comment]
+1

**Pull request merged**
