### PR TITLE
Fix EZP-23215: Add Remove Source button so that relations can be removed from blocks

### PR DESCRIPTION
**Pull request by peterkeung**
Once a source is added to a block, the user needs a way to remove it!

Link: https://jira.ez.no/browse/EZP-23215

### CODE REVIEW

**Comment by thiagocamposviana** [comment]
Indeed a must have feature as it seems natural that sometimes we want to remove a source instead of replacing it.

**Comment by crevillo** [comment]
+1 to the feature. Not tested but code looks good.

**Comment by bgamrat** [comment]
+1 - Helpful feature

**Comment by ernestob** [comment]
:+1: 

I am using blocks with custom attributes and currently there is no way to remove the source, this should be merge ASAP, this is a must have feature.

I don't know who from eZ is in charge of ezflow merges but @dpobel  @andrerom  @lolautruche @bdunogier  merge this pull request.

**Comment by andrerom** [comment]
could someone add a screenshot of the feature?

**Comment by joaoinacio** [comment]
@andrerom: taken from https://jira.ez.no/browse/EZP-23215 :

remove_source

**Comment by andrerom** [comment]
@lserwatka Any input here? see further description and screenshoots in issue.

**Comment by lserwatka** [comment]
+1 looks fine from the code POV. You can merge it.

**Comment by peterkeung** [comment]
The UI might be better with an [x] next to each source, but that could be a future enhancement.

**Comment by ernestob** [comment]
Is anything else needed to this PR to get it merged?

Poking :point_right:: @andrerom @lserwatka @joaoinacio

**Comment by andrerom** [comment]
+1 with backport to 5.4 ping @yannickroger / @joaoinacio

**Comment by yannickroger** [comment]
Thanks @peterkeung

**Comment by ernestob** [comment]
Thanks guys :tada:

**Pull request merged**
