### PR TITLE
Removed include_once() to avoid "Cannot redeclare class"

### PR DESCRIPTION
**Pull request by chs2**

### CODE REVIEW

**Comment by crevillo** [comment]
looks good to me as classes should be autoloaded, but curious about why this hasn't been spotted until now...

**Comment by andrerom** [comment]
+1

but

> looks good to me as classes should be autoloaded, but curious about why this hasn't been spotted until now...

Same, @lserwatka any input once you are back from 😎 🌊 🐚 ?

**Comment by andrerom** [comment]
There are more of them.

Anyone able to verify if they can all be safely removed? @peterkeung @chs2 @crevillo ?
https://github.com/ezsystems/ezflow/search?q=include_once&unscoped_q=include_once

**Comment by andrerom** [comment]
@chs2 Up for doing another PR? :)

**Pull request merged**
